apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: 178621424795.dkr.ecr.us-east-2.amazonaws.com/shubhamr837:eureka-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80