apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: gcr.io/crested-ratio-257703/eureka-pdf:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
